### ISSUE TITLE
Blogpagina opslaan lijkt niet te werken

### ISSUE THREAD

**Issue by Arrangeur** [acidjunk/funder#1]
Ingelogd als Admin:
Als ik de blogpagina 'what's a local fund' aanpas en het concept opsla, de pagina verlaat en later weer terugkom is het concept niet aangepast. Ook 'revisions' geeft aan dat er niets is aangepast.

**Comment by acidjunk** [comment]
Dat knopje zou moeten uitklappen naar save and publish

**Comment by Arrangeur** [comment]
Ik krijg ook de mogelijkheid om op te slaan. CMS denkt dan dat ik van de pagina wil.

![schermafbeelding 2016-09-07 om 17 14 55](https://cloud.githubusercontent.com/assets/22054411/18317547/d27d8b26-751e-11e6-977f-c415fe665c5f.png)

Als ik 'op de pagina blijven' kies, dan werkt de knop een seconde of 10 en lijkt de pagina opgeslagen (aan de knop te zien.

Verlaten en weer terugkomen laat zien dat er niets is veranderd.

**Comment by Arrangeur** [comment]
Idem trouwens bij projecten, waar bij het aanpassen van de kleine kip hetzelfde gebeurt.

**Comment by Arrangeur** [comment]
Met Firefox gaat het wel goed. Krijg nu ook een melding van CMS dat wijzigen is gelukt en geen melding meer van pagina verlaten of niet.

**Comment by Arrangeur** [comment]
Chrome gaat ook goed.

**Comment by acidjunk** [comment]
Ik ga morgen ook een uograde naar Wagtail 1.6 proberen en zal voor/na ff testen met recente versie van Safari.

**Comment by acidjunk** [comment]
Saven werkte ook met vorige versie (bij mij in Safari); maar wagtail 1.6.2 haalt i.i.g. de dialoog weg die zegt dat je de site gaat verlaten. Seems solved for now :)

**Comment by Arrangeur** [comment]
Mooi, op naar de volgende ;-)

R
