### ISSUE TITLE
Picture added to blogpost body messes up homepage blog

### ISSUE THREAD

**Issue by Arrangeur** [acidjunk/funder#2]
![schermafbeelding 2016-09-13 om 10 50 15](https://cloud.githubusercontent.com/assets/22054411/18467441/42f6327e-79a0-11e6-9f76-1b25ea7a3536.png)

Wanneer een afbeelding in de tekst van een blogpost wordt opgenomen, is de post mooi, maar het overzicht van alle posts wordt er door uit het lood gebracht.

**Comment by acidjunk** [comment]
One solution could be to add aan extra filed intro or teaser to blog posts. That field could be used on the blog index page instead of using the blog's main text limited to the first 25 words

**Comment by Arrangeur** [comment]
That sounds like an adequate solution. As such a teaser is also used for projects and products, editors and admins probably would welcome the consistency.

**Comment by acidjunk** [comment]
Fixed with teaser field
