### ISSUE TITLE
Small dutch translation issues

### ISSUE THREAD

**Issue by Arrangeur** [acidjunk/funder#3]
![schermafbeelding 2016-09-13 om 12 04 24](https://cloud.githubusercontent.com/assets/22054411/18469941/7b97dc5e-79aa-11e6-9c17-9f5f18464b6b.png)

Wat kleine tekstuele dingetjes
1. I**k** ga akkoord
2. algemene voorwaarden: zijn die van payprovider of van ons?
3. Cart: remove -> verwijder
4. abonneren i.p.v. abboneren
5. Onder Anoniem: ik kwam hier via het afrekenen van een 'product', niet via project
6. Cart: Mandje, ik weet niet wat gebruikelijk is.
7. Vul het formulier **in** of is er met cookies al iets vooraf ingevuld?

**Comment by acidjunk** [comment]
I will update the translation files soon to fix the typo's

5: The checkout is agnostic/generic; it doesn't know the difference between projects or products.
7: When user already provided name/organisation in the donation forms they will be used to prefill the checkout form

**Comment by Arrangeur** [comment]
Als je me een link geeft naar de vertalingen dan help ik wel.

Mvrgr Rolf

**Comment by acidjunk** [comment]
Theoretisch mogelijk om het direct hier te doen:
https://github.com/acidjunk/funder/blob/master/funder/locale/nl/LC_MESSAGES/django.po

Dan is het niet direct live; dat is het pas nadat ik het opnieuw deploy
