### ISSUE TITLE
Should we make VAT configurable?

### ISSUE THREAD

**Issue by Arrangeur** [acidjunk/funder#4]
In de cart wordt een BTW-bedrag opgeteld bij de prijs van de donatie. Ik denk niet dat dat hoeft. Er zou dus ook een cart moeten zijn die niets doet met BTW.

**Comment by acidjunk** [comment]
I suppose 'to VAT or not to VAT' is  related to type of donation. When I want to donate from a BV or other profit company I need a receipt and price which includes VAT. When I do the same donation from a non profit organisation: it doesn't have VAT. Best option seems to be to make it configurable.

**Comment by acidjunk** [comment]
VAT can be turned on/off from application settings. Turned off by default.
